// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkjji-nlI8q0CJff-F-WtqmRd1_3vos1Q',
    appId: '1:780810782870:android:b0c2c994e38f8d56471ab7',
    messagingSenderId: '780810782870',
    projectId: 'gem-prod-91ada',
    storageBucket: 'gem-prod-91ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw6bi7dmX2XWaOWocDqZoFDISZnQEhKJA',
    appId: '1:780810782870:ios:6596c7b226bf6151471ab7',
    messagingSenderId: '780810782870',
    projectId: 'gem-prod-91ada',
    storageBucket: 'gem-prod-91ada.firebasestorage.app',
    androidClientId: '780810782870-6gvqhdmofrffjtu9lbia8g8dta0aoafu.apps.googleusercontent.com',
    iosClientId: '780810782870-2foaeqg6fb5j2s16p7ffhqas6iov9rf3.apps.googleusercontent.com',
    iosBundleId: 'com.rijan.goExtraMile',
  );

}